version: "2.3"
services:
  plasma-contracts:
    image: omisegoimages/${IMAGE}
    command:
      - /bin/sh
      - -c
      - |
          apk add --update curl
          cd /home/node/plasma-contracts/plasma_framework
          # Fix block gas limit issue by retrying truffle migration up to 5 times
          for i in 1 2 3 4 5; do \
            echo 'Running truffle migration attempt #$${i}'
            npx truffle migrate --network remote command && break; \
          done
          cd build
          echo '{"contracts":' > db.json && cat outputs.json >> db.json && echo '}' >> db.json
          npx json-server -w db.json -p 8000 -H 0.0.0.0
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ${PWD}/plasma-contracts/contracts/:/home/node/plasma-contracts/plasma_framework/build/contracts/
      - ${PWD}/plasma-contracts/build/db.json:/home/node/plasma-contracts/plasma_framework/build/db.json
    environment:
      # DEPLOYER_PRIVATEKEY is the geth dev account initially funded address
      - DEPLOYER_PRIVATEKEY=d885a307e35738f773d8c9c63c7a3f3977819274638d04aaf934a1e1158513ce # 0x6De4b3B9C28E9C3e84c2b2d3a875C947a84de68D
      - MAINTAINER_PRIVATEKEY=e91a81533b61281b920784e0bad25c19b3671639d86e643bf1e60ec8c2244f8a # 0x249887184fa60f91a213d40efec358161abc1f0d
      - AUTHORITY_PRIVATEKEY=7f30f140fd4724519e5017c0895f158d68bbbe4a81c0c10dbb25a0006e348807 # 0xC0f780DfC35075979B0DEF588d999225B7ecC56f
      - REMOTE_URL=http://geth:8545
      - DEPLOY_TEST_CONTRACTS=true
      - MIN_EXIT_PERIOD=${MIN_EXIT_PERIOD}
    depends_on:
      geth:
        condition: service_healthy
    restart: always
    healthcheck:
      test: curl plasma-contracts:8000/contracts
      interval: 60s
      timeout: 15s
      retries: 10
      start_period: 5m

  geth:
    image: ethereum/client-go:v1.9.10
    entrypoint:
      - /bin/sh
      - -c
      - |
          
          apk add --update curl
          # Configures geth with the deployer and authority accounts. This includes:
          #   1. Configuring the deployer's keystore
          #   2. Configuring the authority's keystore
          #   3. Configuring the keystores' password
          #   4. Unlocking the accounts by their indexes
          geth --datadir data/ init data/geth/genesis.json
          echo "" > /tmp/geth-blank-password
          # Starts geth
          
          geth --miner.gastarget 7500000 \
            --miner.gasprice "10" \
            --datadir data/ \
            --syncmode 'full' \
            --networkid 1337 \
            --gasprice '1' \
            --keystore=./data/geth/keystore/ \
            --password /tmp/geth-blank-password \
            --unlock "0,1" \
            --rpc --rpcapi personal,web3,eth,net --rpcaddr 0.0.0.0 --rpcvhosts=* --rpcport=8545 \
            --ws --wsaddr 0.0.0.0 --wsorigins='*' \
            --mine \
            --allow-insecure-unlock
            
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8546"
      - "8545"
    volumes:
      - ./data:/data
    healthcheck:
      test: curl geth:8545
      interval: 5s
      timeout: 3s
      retries: 5