version: "2.3"
services:
  plasma-contracts:
    image: omisegoimages/${IMAGE}
    command:
      - /bin/sh
      - -c
      - |
          # deploy the multisig
          cd /home/node/plasma-contracts/MultiSigWallet
          npx truffle migrate --accounts 0x6De4b3B9C28E9C3e84c2b2d3a875C947a84de68D --confirmations 1 --network remote
          apk add --update curl
          cd /home/node/plasma-contracts/plasma_framework
          # Fix block gas limit issue by retrying truffle migration up to 5 times
          npx truffle version
          export VAULT_TOKEN=$$(cat /tmp/unseal.json | jq -r .root_token)
          echo $$VAULT_TOKEN
          for i in 1 2 3 4 5; do \
            echo 'Running truffle migration attempt #$${i}'
            npx truffle migrate --network remote command && break; \
          done
          cd build
          echo '{"contracts":' > db.json && cat outputs.json >> db.json && echo '}' >> db.json
          npx json-server -w db.json -p 8000 -H 0.0.0.0
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ${PWD}/plasma-contracts/contracts/:/home/node/plasma-contracts/plasma_framework/build/contracts/
      - ${PWD}/plasma-contracts/build/db.json:/home/node/plasma-contracts/plasma_framework/build/db.json
      - "./immutability/config:/tmp:rw"
    environment:
      # DEPLOYER_PRIVATEKEY is the geth dev account initially funded address
      - DEPLOYER_PRIVATEKEY=d885a307e35738f773d8c9c63c7a3f3977819274638d04aaf934a1e1158513ce # 0x6De4b3B9C28E9C3e84c2b2d3a875C947a84de68D
      - MAINTAINER_PRIVATEKEY=e91a81533b61281b920784e0bad25c19b3671639d86e643bf1e60ec8c2244f8a # 0x249887184fa60f91a213d40efec358161abc1f0d
      - AUTHORITY_PRIVATEKEY=7f30f140fd4724519e5017c0895f158d68bbbe4a81c0c10dbb25a0006e348807 # 0xC0f780DfC35075979B0DEF588d999225B7ecC56f
      - REMOTE_URL=http://geth:8545
      - DEPLOY_TEST_CONTRACTS=true
      - MIN_EXIT_PERIOD=${MIN_EXIT_PERIOD}
      # HEY THIS IS IMPORTANT
      - VAULT=false
      - VAULT_ADDR=https://vault_server:8200
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - VAULT_RPC_REMOTE_URL=http://geth:8545
      - CHAIN_ID=1337
    env_file: ../tester/CONTRACT_EXPERIMENTAL_FEATURES
    depends_on:
      geth:
        condition: service_healthy
      vault_server:
        condition: service_healthy
    restart: always
    healthcheck:
      test: curl plasma-contracts:8000/contracts
      interval: 60s
      timeout: 15s
      retries: 10
      start_period: 5m

  geth:
    image: ethereum/client-go:v1.9.15
    entrypoint: /bin/sh -c ". data/command"
    ports:
      - "8545:8545"
      - "8546:8546"
    expose:
      - "8546"
      - "8545"
    volumes:
      - ./data:/data
    healthcheck:
      test: curl geth:8545
      interval: 5s
      timeout: 3s
      retries: 5

  vault_server:
    image: gcr.io/omisego-development/omgnetwork/vault:0.0.7
    entrypoint: >
      /bin/sh -c "
        sleep 2

        /vault/config/entrypoint.sh
      "
    ports:
      - "8200:8200"
    links:
      - "geth"
    volumes:
      - "./immutability/ca:/vault/ca:rw"
      - "./immutability/ca/certs/:/etc/ssl/certs/"
      - "./immutability/config:/vault/config:rw"
    healthcheck:
      test: vault status --tls-skip-verify
      interval: 5s
      timeout: 3s
      retries: 5

