FROM alpine:3.11

ARG RUST_VERSION="1.46.0"

RUN RUN apk add --no-cache gcc musl-dev

ADD ./rustup.sh ./rustup.sh
RUN chmod u+x ./rustup.sh
RUN ./rustup.sh -y

ENV PATH=/root/.cargo/bin:$PATH
RUN rustup toolchain install ${RUST_VERSION}
RUN rustup default ${RUST_VERSION}
