FROM alpine:3.11

ARG RUST_VERSION="1.46.0"

ADD ./rustup.sh ./rustup.sh
RUN chmod u+x ./rustup.sh
RUN ./rustup.sh | sh -s -- -y

ENV PATH=/root/.cargo/bin:$PATH

RUN rustup toolchain install ${RUST_VERSION}
